name: Windows Runner Test

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP
        shell: powershell
        run: |

          Compress-Archive `
            -Path .\* `
            -DestinationPath app.zip `
            -Force

      - name: Verify ZIP
        shell: powershell
        run: |

          Get-ChildItem

      - name: Copy ZIP To Target Server
        shell: powershell
        run: |

          Copy-Item `
            "app.zip" `
            "\\172.31.29.167\C$\services\app.zip" `
            -Force

      - name: Extract ZIP On Target Server
        shell: powershell
        run: |

          Invoke-Command `
            -ComputerName 172.31.29.167 `
            -ScriptBlock {

              Expand-Archive `
                -Path "C:\services\app.zip" `
                -DestinationPath "C:\services\current" `
                -Force

              Write-Host "Deployment Successful"

          }
